version: '3.4'

networks:
  cloudyourself_network:
    driver: bridge

services:

  gateways_selfserviceportalapi:
    image: cloud-yourself.gateways.selfserviceportalapi
    container_name: "CloudYourself-Gateways-SelfServicePortalApi"
    networks:
      - cloudyourself_network
    ports:
      - "4100:4100"
    environment:
      ASPNETCORE_URLS: 'http://*:4100'
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: ./Gateways/SelfServicePortalApi/Src/
      dockerfile: Dockerfile.debug
    volumes: 
      - ../Infrastructure/Config/General:/app/config/general
      - ../Infrastructure/Config/AppSpecific:/app/config/appspecific

  gateways_automationapi:
    image: cloud-yourself.gateways.automationapi
    container_name: "CloudYourself-Gateways-AutomationApi"
    networks:
      - cloudyourself_network
    ports:
      - "4101:4101"
    environment:
      ASPNETCORE_URLS: 'http://*:4101'
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: ./Gateways/AutomationApi/Src/
      dockerfile: Dockerfile.debug
    volumes: 
      - ../Infrastructure/Config/General:/app/config/general
      - ../Infrastructure/Config/AppSpecific:/app/config/appspecific

  appservices_masterdata:
    image: cloud-yourself.appservices.masterdata
    container_name: "CloudYourself-AppServices-MasterData"
    networks:
      - cloudyourself_network
    ports:
      - "4000:4000"
    environment:
      ASPNETCORE_URLS: 'http://*:4000'
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: ./AppServices/MasterData/Src/
      dockerfile: Dockerfile.debug
    volumes: 
      - ../Infrastructure/Config/General:/app/config/general
      - ../Infrastructure/Config/AppSpecific:/app/config/appspecific

  appservices_azure:
    image: cloud-yourself.appservices.azure
    container_name: "CloudYourself-AppServices-Azure"
    networks:
      - cloudyourself_network
    ports:
      - "4001:4001"
    environment:
      ASPNETCORE_URLS: 'http://*:4001'
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: ./AppServices/Azure/Src/
      dockerfile: Dockerfile.debug
    volumes: 
      - ../Infrastructure/Config/General:/app/config/general
      - ../Infrastructure/Config/AppSpecific:/app/config/appspecific

  appservices_billing:
    image: cloud-yourself.appservices.billing
    container_name: "CloudYourself-AppServices-Billing"
    networks:
      - cloudyourself_network
    ports:
      - "4002:4002"
    environment:
      ASPNETCORE_URLS: 'http://*:4002'
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: ./AppServices/Billing/Src/
      dockerfile: Dockerfile.debug
    volumes: 
      - ../Infrastructure/Config/General:/app/config/general
      - ../Infrastructure/Config/AppSpecific:/app/config/appspecific

  appservices_aws:
    image: cloud-yourself.appservices.aws
    container_name: "CloudYourself-AppServices-AWS"
    networks:
      - cloudyourself_network
    ports:
      - "4003:4003"
    environment:
      ASPNETCORE_URLS: 'http://*:4003'
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: ./AppServices/Aws/Src/
      dockerfile: Dockerfile.debug
    volumes: 
      - ../Infrastructure/Config/General:/app/config/general
      - ../Infrastructure/Config/AppSpecific:/app/config/appspecific
  
  infrastructure_sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
    container_name: "CloudYourself-Infrastructure-SqlExpress"
    networks:
      - cloudyourself_network
    ports: 
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Start@1357"
      MSSQL_PID: "Express"

