trigger:
  branches:
    include:
    - feature/*
    - enabler/*
    - bugfix/*
    - master
  paths:
    include:
    - /Backend/AppServices/Aws/
extends:
  template: ../../../Infrastructure/Pipelines/dotnet-docker-image.yaml
  parameters:
    projectPath: 'Backend/AppServices/Aws'
    imageName: 'cloudyourself-appservices-aws'
    imageTag: '$(Build.BuildId)'