trigger:
  branches:
    include:
    - feature/*
    - enabler/*
    - bugfix/*
    - master
  paths:
    include:
    - /Backend/AppServices/Billing/
extends:
  template: ../../../Infrastructure/Pipelines/dotnet-docker-image.yaml
  parameters:
    projectPath: 'Backend/AppServices/Billing'
    imageName: 'cloudyourself-appservices-billing'
    imageTag: '$(Build.BuildId)'