apiVersion: apps/v1
kind: Deployment
metadata:
  name: appservices-billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appservices-billing
  template:
    metadata:
      labels:
        app: appservices-billing
    spec:
      containers:
      - name: appservices-billing
        image: cloudyourselfcontainers.azurecr.io/#{imageName}#:#{imageTag}#
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:80"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: general-config
          mountPath: /app/config/general
        - name: appspecific-config
          mountPath: /app/config/appspecific
      volumes: 
      - name: general-config
        secret:
          secretName: general-config
      - name: appspecific-config
        secret:
          secretName: backend-appservices-billing-config
---
apiVersion: v1
kind: Service
metadata:
  name: appservices-billing
spec:
  ports:
  - port: 80
  selector:
    app: appservices-billing