trigger:
  branches:
    include:
    - feature/*
    - enabler/*
    - bugfix/*
    - master
  paths:
    include:
    - /Backend/AppServices/Azure/
extends:
  template: ../../../Infrastructure/Pipelines/dotnet-docker-image.yaml
  parameters:
    projectPath: 'Backend/AppServices/Azure'
    imageName: 'cloudyourself-appservices-azure'
    imageTag: '$(Build.BuildId)'